### ISSUE TITLE
/notice/write 글 작성 시 E500 또는 타임아웃 에러 출력

### ISSUE THREAD

**Issue by gaon12** [gaon12/eureka#16]
민원, 공지사항 작성 시, `category`, `title`, `content`를 모두 포함하여 작성했음에도 서버에서는 E500 또는 타임아웃이 됩니다.

1. `content`가 짧을 경우에는 E500 에러 출력
2. `content`가 충분히 긴 경우에는 타임아웃 발생

해결 부탁드립니다.

**Comment by vwaiolet** [comment]
2번은 해결 했습니다

**Comment by vwaiolet** [comment]
1번은 요약 실패 시 입력된 값 그대로 저장하도록 변경했습니다
