### ISSUE TITLE
같은 브라우저, 같은 세션, 같은 아이디 및 비밀번호 시 중복 로그인 안되도록

### ISSUE THREAD

**Issue by gaon12** [gaon12/eureka#17]
로그인을 한 상태에서 같은 브라우저, 같은 세션 상태에서, 같은 아이디 및 비밀번호로 로그인 시도 시 로그인이 됩니다.

확인 후 의도된 사항이라면 ___wontfix___ 라벨 달아주시고 close 해주시면 감사하겠습니다.

**Comment by vwaiolet** [comment]
로그인 로직 변경 예정입니다.
변경 완료 후 적용해보도록 하겠습니다

**Comment by vwaiolet** [comment]
중복 로그인 방지 로직 적용하였습니다
