### ISSUE TITLE
차량 등록 대기 중인 번호를 등록 신청 시 등뢱된 차량이라 뜨는 문제

### ISSUE THREAD

**Issue by gaon12** [gaon12/eureka#19]
차량 등록 메뉴에서 차량번호를 등록 신청하고, 승인 또는 거부하기 전에 사용자가 같은 차량번호를 등록 신청하면 '이미 등록된 차량번호' 라고 뜹니다.

**Comment by vwaiolet** [comment]
같은 차량 번호로 신청하면 승인 대기 중 차량 이라는 메시지를 반환하도록 개선하였습니다

**Comment by gaon12** [comment]
등록된 차량을 등록 신청하면 **등록 실패: ** 이렇게만 뜹니다.

![image](https://github.com/gaon12/eureka/assets/34927797/82bcdac0-3a55-466f-a787-15a4c3f674f7)

**Comment by vwaiolet** [comment]
응답 메시지는 이미 등록 된 차량이라고 반환되는 것을 확인했습니다. 프론트 측에 문의해주세요

**Comment by gaon12** [comment]
> 응답 메시지는 이미 등록 된 차량이라고 반환되는 것을 확인했습니다. 프론트 측에 문의해주세요

앗! 그렇군요. 프론트 담당분들 Assignees 걸어 놓고, 확인할 수 있도록 이슈 재 오픈하겠습니다.

**Comment by dong0424** [comment]
문제점을 확인을 하였고 최대한 그 문제점을 고치도록 조치를 하겠습니다.

**Comment by vwaiolet** [comment]
23.09.04 14:25 테스트 결과 정상 작동 확인하였습니다
