### ISSUE TITLE
프론트엔드 로그인 처리 버그

### ISSUE THREAD

**Issue by gaon12** [gaon12/eureka#22]
1. 로그인 후 새로고침 또는 새 탭으로 현재 도메인 입력 후 접속 시 로그인 화면으로 넘어갑니다.
2. 로그인이 된 상태로 로그인 화면에 접속 후, 동/호/비밀번호를 입력하면 '서버로부터 메시지를 받지 못했습니다.' 이런 메시지가 뜹니다. 서버에서는
```json
{
   "status":400,
   "error":{
      "errorCode":"E406",
      "message":"이미 로그인 되어 있음"
   }
}
```
이렇게 반환이 됩니다.
3. 이 상태에서 쿠키값을 삭제 후 로그인을 재시도 하면 로그인이 잘 됩니다.

**Comment by vwaiolet** [comment]
다른 서비스들도 확인 결과 같은 현상이 발생하여 정상적인 동작으로 판단됩니다
