### ISSUE TITLE
번호판 인식 코드 수정

### ISSUE THREAD

**Issue by dong0424** [gaon12/eureka#3]
구형 번호판을 인식이 되도록 했습니다. 아직 테스트를 할부분이 있고 인식률을 높이겠습니다.
https://github.com/gaon12/eureka/tree/main/detect
commit을 할려고 했는데 잘안되서 우선은 경로를 보냈습니다.

**Comment by gaon12** [comment]
#1 이슈로 옮기고 본 이슈는 close 하겠습니다.
