### ISSUE TITLE
회원가입 자바스크립트 서버 검증값 반환 추가

### ISSUE THREAD

**Issue by gaon12** [gaon12/eureka#6]
e8bb425eee4a59018957d6ee0dfb35af64427036 커밋으로 회원가입시 결과를 자바스크립트를 사용해 서버에 전달하는 코드를 작성했습니다. 다만 중복 가입 등 서버에서 검증하고, 결과를 반환하면 그 값을 적절히 처리하도록 하겠습니다.

**Comment by vwaiolet** [comment]
동호수가 이미 DB에 존재하는지 확인하는 로직 추가하였고, 결과 반환하는 코드는 추후 추가 예정

**Comment by vwaiolet** [comment]
개발 완료 된 검증코드
1. 이미 가입한 세대인지 확인
2. 비밀번호와 비밀번호 확인이 일치하는지 확인
3. 필수항목이 모두 입력되었는지 확인

결과를 JSON 형식으로 반환
