### ISSUE TITLE
DB 설계도

### ISSUE THREAD

**Issue by vwaiolet** [gaon12/eureka#7]
![aptManager](https://github.com/gaon12/eureka/assets/67896210/a8d4c742-c9c5-4108-a7d5-127c19fe67ef)

**Comment by gaon12** [comment]
![image](https://github.com/gaon12/eureka/assets/34927797/79c26257-c6cc-4e1e-82dd-416ccbd7f42e)
이슈 페이지 상에서 이미지가 깨지는데, 링크 추가해 주시면 감사하겠습니다!

**Comment by vwaiolet** [comment]
![aptManager (1)](https://github.com/gaon12/eureka/assets/67896210/e7fdbb1e-3431-4564-959b-601131519cbb)
