### ISSUE TITLE
오류/상태/기능 코드 추가 건의

### ISSUE THREAD

**Issue by gaon12** [gaon12/eureka#8]
메시지 뿐만 아니라 오류/상태/기능 코드를 추가하는 것을 건의합니다.

디버깅 뿐만 아니라 나중에 오류 통계를 낼 때에도 사용할 예정입니다.

각 통신과정 모두에 추가하면 좋을 것 같습니다. 각 코드와 설명은 위키에 적어주시면 감사하겠습니다!

**Comment by vwaiolet** [comment]
main 브랜치 node 폴더 README로 업로드 되었습니다
