### ISSUE TITLE
차량 정보 조회 API

### ISSUE THREAD

**Issue by vwaiolet** [gaon12/eureka#9]
서버로 어떤식으로 요청을 줄지, 요청을 처리한 후 어떤 정보를 반환할 지 협의 필요

개인적으로 바라는 요청 방식은 
``` JSON
{
  "car_number": "차량 번호"
}
```
이고, 반환도 JSON 형식으로 반환

**Comment by vwaiolet** [comment]
번호판 정보를 입력받으면 차량 테이블이 담고 있는 정보 중 어떤 정보를 반환하면 되는건지 물어본거였습니다. 모든 정보를 반환하면 되는건지

모든 정보를 반환하게 된다면
- 차량 소유자 정보
- 손님 여부
- 전기차 여부
- 장애인 차량 여부
- 등록 신청 일시
- 등록 승인 일시
- 등록 여부

위와 같은 정보 반환하게 됩니다

**Comment by gaon12** [comment]
> 번호판 정보를 입력받으면 차량 테이블이 담고 있는 정보 중 어떤 정보를 반환하면 되는건지 물어본거였습니다. 모든 정보를 반환하면 되는건지
> 
> 
> 
> 모든 정보를 반환하게 된다면
> 
> - 차량 소유자 정보
> 
> - 손님 여부
> 
> - 전기차 여부
> 
> - 장애인 차량 여부
> 
> - 등록 신청 일시
> 
> - 등록 승인 일시
> 
> - 등록 여부
> 
> 
> 
> 위와 같은 정보 반환하게 됩니다

아, 저는 Flask 서버 -> Node.js 서버에 값을 보낼 때를 말하는 줄 알았네요. 그렇게 하면 될 거 같아요.

**Comment by vwaiolet** [comment]
main 브랜치 node 폴더에 업로드 되었습니다
